//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.27 at 02:30:58 PM CST 
//


package elong;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HotelGiftHourTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HotelGiftHourTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Hours24"/>
 *     &lt;enumeration value="XHourBefore"/>
 *     &lt;enumeration value="XHourAfter"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HotelGiftHourTypeEnum")
@XmlEnum
public enum HotelGiftHourTypeEnum {

    @XmlEnumValue("Hours24")
    Hours24("Hours24"),
    @XmlEnumValue("XHourBefore")
    XHourBefore("XHourBefore"),
    @XmlEnumValue("XHourAfter")
    XHourAfter("XHourAfter");
    private final String value;

    HotelGiftHourTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HotelGiftHourTypeEnum fromValue(String v) {
        for (HotelGiftHourTypeEnum c: HotelGiftHourTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
