//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.22 at 03:43:24 PM CST 
//


package elong;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement; 
import java.util.List; 
import com.alibaba.fastjson.annotation.JSONField;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HotelGeos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HotelGeos">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HotelGeoList" type="{}ArrayOfHotelGeoXML" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelGeos", propOrder = {
    "hotelGeoList"
})
public class HotelGeos {

    @JSONField(name = "HotelGeoList")
    protected List<HotelGeoXML> hotelGeoList;

    /**
     * Gets the value of the hotelGeoList property.
     * 
     * @return
     *     possible object is
     *     {@link List<HotelGeoXML> }
     *     
     */
    public List<HotelGeoXML> getHotelGeoList() {
        return hotelGeoList;
    }

    /**
     * Sets the value of the hotelGeoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link List<HotelGeoXML> }
     *     
     */
    public void setHotelGeoList(List<HotelGeoXML> value) {
        this.hotelGeoList = value;
    }

}
