//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 10:29:41 AM CST 
//


package elong;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement; 
import java.util.List; 
import com.alibaba.fastjson.annotation.JSONField;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.Date;


/**
 * <p>Java class for IsOntimeConfirmRoom complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IsOntimeConfirmRoom">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SHotelID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SRoomTypeID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SSuffixName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Op_Date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="IsOntimeConfirm" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IsOntimeConfirmRoom", propOrder = {
    "sHotelID",
    "sRoomTypeID",
    "sSuffixName",
    "opDate",
    "isOntimeConfirm"
})
public class IsOntimeConfirmRoom {

    @JSONField(name = "SHotelID")
    protected String sHotelID;
    @JSONField(name = "SRoomTypeID")
    protected String sRoomTypeID;
    @JSONField(name = "SSuffixName")
    protected String sSuffixName;
    @JSONField(name = "Op_Date")
    @XmlSchemaType(name = "dateTime")
    protected java.util.Date opDate;
    @JSONField(name = "IsOntimeConfirm")
    protected boolean isOntimeConfirm;

    /**
     * Gets the value of the sHotelID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHotelID() {
        return sHotelID;
    }

    /**
     * Sets the value of the sHotelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHotelID(String value) {
        this.sHotelID = value;
    }

    /**
     * Gets the value of the sRoomTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSRoomTypeID() {
        return sRoomTypeID;
    }

    /**
     * Sets the value of the sRoomTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSRoomTypeID(String value) {
        this.sRoomTypeID = value;
    }

    /**
     * Gets the value of the sSuffixName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSuffixName() {
        return sSuffixName;
    }

    /**
     * Sets the value of the sSuffixName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSuffixName(String value) {
        this.sSuffixName = value;
    }

    /**
     * Gets the value of the opDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.util.Date }
     *     
     */
    public java.util.Date getOpDate() {
        return opDate;
    }

    /**
     * Sets the value of the opDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.util.Date }
     *     
     */
    public void setOpDate(java.util.Date value) {
        this.opDate = value;
    }

    /**
     * Gets the value of the isOntimeConfirm property.
     * 
     */
    public boolean isIsOntimeConfirm() {
        return isOntimeConfirm;
    }

    /**
     * Sets the value of the isOntimeConfirm property.
     * 
     */
    public void setIsOntimeConfirm(boolean value) {
        this.isOntimeConfirm = value;
    }

}
